name: Pico Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential gcc-arm-none-eabi
      - name: Clone Pico SDK
        run: |
          git clone --depth 1 --branch 2.1.1 https://github.com/raspberrypi/pico-sdk.git $GITHUB_WORKSPACE/pico-sdk
          cd $GITHUB_WORKSPACE/pico-sdk
          git submodule update --init
      - name: Configure
        run: cmake -B build -S . -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk
      - name: Build
        run: cmake --build build --parallel 